### ISSUE TITLE
Vertical Split color

### ISSUE THREAD

**Issue by qauff** [lighthaus-theme/vim-lighthaus#3]
I just installed this lovely theme, and I noticed that the vertical split line I've got is not dashed like in the screenshot:

![](https://github.com/lighthaus-theme/vim/raw/master/assets/vim1.png?raw=true)

mine:
![](https://i.imgur.com/IkEP7aU.png)

How do I get the dashed line? is it a specific font? Perhaps we can have `s:vsplit_fg` use `s:black` or something much more subtle than that harsh `white2`. Is there a way for me to override this in my `.vimrc`?

**Comment by lighthaus-theme** [comment]
> I just installed this lovely theme

Thank you so much!!

> I noticed that the vertical split line I've got is not dashed like in the screenshot:

So that dash/line depends on the font you are using. I am using Nerd Font Medium and for me the line got rendered as _dashed_.

What font as you using?

you can define the character to be used for the separator with the following line in your vimrc
`set fillchars=vert:\│`

Just to try out, may be put `+` as the character and test it out to make sure.

> Perhaps we can have s:vsplit_fg use s:black or something much more subtle than that harsh white2

You are right about this, white2 is very harsh as a separator in a continuous line.

Black on the other hand is a bit too subdued, barely see the difference.

One solution is I could swap white2 to `hl_bg: #090B26`. Much more subdued as compared to white2 and still not completely washed out.

**Comment by lighthaus-theme** [comment]
This is what `hl_bg: #090B26` would look like.

<a href="https://imgur.com/urrzmgD"><img src="https://i.imgur.com/urrzmgD.png" title="source: imgur.com" /></a>

**Comment by qauff** [comment]
I love it, that's a great choice 😍

**Comment by lighthaus-theme** [comment]
> I love it, that's a great choice 😍

Thank you!

Thanks for pointing out this issue. I am also adding a few more coc options, so will put a fix for this issues along with that and push it later today hopefully.

**Comment by lighthaus-theme** [comment]
Added an option to toggle vertical split line color.
Default color is now dark. 

It can be changed using this option: `let g:lighthaus_vsplit_line_light = 1`

Have updated the README with the info as well.
